// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("App");

function make(name, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "App"
                }, React.createElement("header", {
                      className: "App-header"
                    }, React.createElement("h1", undefined, name)));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
