// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var $$Array              = require("bs-platform/lib/js/array.js");
var React                = require("react");
var ReasonReact          = require("reason-react/lib/js/src/reasonReact.js");
var GitHubRepositoryItem = require("./gitHubRepositoryItem.js");

var component = ReasonReact.statelessComponent("GitHubRepositoryList");

function make(repositories, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "GitHubRepositoryList"
                }, $$Array.map((function (repository) {
                        return ReasonReact.element(/* Some */[repository[/* id */0]], /* None */0, GitHubRepositoryItem.make(repository, /* array */[]));
                      }), repositories));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
