// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("bs-json/lib/js/src/json_decode.js");

var github_repos_url = "https://api.github.com/search/repositories?q=topic%3Areasonml&type=Repositories";

function parse_repository_json(json) {
  return /* record */[
          /* id */Json_decode.field("full_name", Json_decode.string, json),
          /* full_name */Json_decode.field("full_name", Json_decode.string, json),
          /* stargazers_count */Json_decode.field("stargazers_count", Json_decode.$$int, json),
          /* html_url */Json_decode.field("html_url", Json_decode.string, json)
        ];
}

function parse_repository_response_json(json) {
  return Json_decode.field("items", (function (param) {
                return Json_decode.array(parse_repository_json, param);
              }), json);
}

function fetch_repositories() {
  return fetch(github_repos_url).then((function (prim) {
                  return prim.text();
                })).then((function (json_text) {
                return Promise.resolve(parse_repository_response_json(JSON.parse(json_text)));
              }));
}

exports.github_repos_url               = github_repos_url;
exports.parse_repository_json          = parse_repository_json;
exports.parse_repository_response_json = parse_repository_response_json;
exports.fetch_repositories             = fetch_repositories;
/* No side effect */
