// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("bs-json/lib/js/src/json_decode.js");

function parse_repository_json(json) {
  return /* record */[
          /* id */Json_decode.field("full_name", Json_decode.string, json),
          /* full_name */Json_decode.field("full_name", Json_decode.string, json),
          /* stargazers_count */Json_decode.field("stargazers_count", Json_decode.$$int, json),
          /* html_url */Json_decode.field("html_url", Json_decode.string, json)
        ];
}

exports.parse_repository_json = parse_repository_json;
/* No side effect */
