// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var React                = require("react");
var ReasonReact          = require("reason-react/lib/js/src/reasonReact.js");
var RepositoryData       = require("./repositoryData.js");
var GitHubRepositoryList = require("./gitHubRepositoryList.js");

var dummy_repo = RepositoryData.parse_repository_json(JSON.parse("\n      {\n        \"id\": \"1\",\n        \"full_name\": \"test name\",\n        \"stargazers_count\": 129,\n        \"html_url\": \"https://github.com/mmiszy/reason-react-github-list\"\n      }\n    "));

var component = ReasonReact.statefulComponent("App");

function make(name, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (param) {
      var match = param[/* state */3][/* repositories */0];
      var repositoryItem = match ? ReasonReact.element(/* None */0, /* None */0, GitHubRepositoryList.make(match[0], /* array */[])) : React.createElement("div", undefined, "Loading…");
      return React.createElement("div", {
                  className: "App"
                }, React.createElement("header", {
                      className: "App-header"
                    }, React.createElement("h1", undefined, name)), repositoryItem);
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* repositories : Some */[/* array */[dummy_repo]]];
    });
  return newrecord;
}

exports.dummy_repo = dummy_repo;
exports.component  = component;
exports.make       = make;
/* dummy_repo Not a pure module */
