// Generated by BUCKLESCRIPT VERSION 1.8.1, PLEASE EDIT WITH CARE
'use strict';

var Block                = require("bs-platform/lib/js/block.js");
var Curry                = require("bs-platform/lib/js/curry.js");
var React                = require("react");
var ReasonReact          = require("reason-react/lib/js/src/reasonReact.js");
var RepositoryData       = require("./repositoryData.js");
var GitHubRepositoryList = require("./gitHubRepositoryList.js");

function handleReposLoaded(repos, _) {
  return /* Update */Block.__(0, [/* record */[/* repositories : Some */[repos]]]);
}

var component = ReasonReact.statefulComponent("App");

function make(name, _) {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (self) {
      RepositoryData.fetch_repositories(/* () */0).then((function (repos) {
              Curry._2(self[/* update */2], handleReposLoaded, repos);
              return Promise.resolve(/* () */0);
            }));
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (param) {
      var match = param[/* state */3][/* repositories */0];
      var repositoryItem = match ? ReasonReact.element(/* None */0, /* None */0, GitHubRepositoryList.make(match[0], /* array */[])) : React.createElement("div", undefined, "Loading…");
      return React.createElement("div", {
                  className: "App"
                }, React.createElement("header", {
                      className: "App-header"
                    }, React.createElement("h1", undefined, name)), repositoryItem);
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* repositories : None */0];
    });
  return newrecord;
}

exports.handleReposLoaded = handleReposLoaded;
exports.component         = component;
exports.make              = make;
/* component Not a pure module */
